library(sf)
source("scr/01-run_SPI_computation.r")

# Get array number from command line
# rm(list = ls())
ARRAY_ID <- as.integer(Sys.getenv("SLURM_ARRAY_TASK_ID"))

#------------------------------------------------------------------------------
# 0. PARAMS
#------------------------------------------------------------------------------
PROTECTED_AREA_TYPE = "" # Types of protected areas to consider (unique(aires_prot$DESIG_GR))
UNION = TRUE # Union of protected areas ?
YEARS_LIST <- c(1876, 1900, 1919, 1925, 1927, 1931, 1937, 1938, 1941, 1955, 1960, 1970, 1972, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023)
SPECIES_LIST <- c("Acipenser fulvescens", "Acipenser oxyrinchus", "Agastache nepetoides", 
    "Agoseris aurantiaca var. aurantiaca", "Agrimonia pubescens", 
    "Alasmidonta marginata", "Alchemilla alpina", "Alnus serrulata", 
    "Aloina brevirostris", "Alosa sapidissima", "Ameiurus natalis", 
    "Amelanchier amabilis", "Ammocrypta pellucida", "Ammodramus savannarum pratensis", 
    "Ammospiza nelsoni", "Anchistea virginica", "Andersonglossum boreale", 
    "Andreaea crassinervia", "Andreaea nivalis", "Aneura maxima", 
    "Antennaria rosea subsp. confinis", "Anthoceros agrestis", "Aongstroemia longipes", 
    "Apalone spinifera", "Apopellia endiviifolia", "Arctoa anderssonii", 
    "Arisaema dracontium", "Aristida basiramea", "Arnica chamissonis", 
    "Arnica griscomii subsp. griscomii", "Arnica lanceolata subsp. lanceolata -p03, p05, p12", 
    "Artemisia tilesii", "Asclepias exaltata", "Asclepias tuberosa var. interior", 
    "Asio flammeus", "Aspidotis densa", "Asplenium platyneuron", 
    "Asplenium rhizophyllum", "Asplenium ruta-muraria var. cryptolepis", 
    "Asterella tenella", "Astragalus americanus", "Astragalus australis var. glabriusculus", 
    "Astragalus robbinsii var. fernaldii", "Aulacomnium androgynum", 
    "Bartonia virginica", "Biantheridion undulifolium", "Bidens heterodoxa", 
    "Boechera collinsii", "Boechera quebecensis", "Borodinia canadensis", 
    "Borodinia laevigata", "Botrychium ascendens", "Botrychium campestre var. lineare", 
    "Botrychium michiganense", "Botrychium mormo", "Botrychium pallidum", 
    "Botrychium pedunculosum", "Botrychium pinnatum", "Botrychium spathulatum", 
    "Brachythecium glaciale", "Braya humilis subsp. humilis", "Braya linearis", 
    "Bromus pubescens", "Bryum elegans", "Bryum gemmiparum", "Bryum knowltonii", 
    "Bryum longisetum", "Bryum marratii", "Bryum rubens", "Bryum warneum", 
    "Bucephala islandica pop. 1", "Buxbaumia piperi", "Calidris canutus rufa", 
    "Campylopus schimperi", "Campylostelium saxicola", "Canadanthus modestus", 
    "Cardamine bulbosa", "Carex annectens", "Carex argyrantha", "Carex atherodes", 
    "Carex atlantica subsp. capillacea", "Carex baileyi", "Carex cephalophora", 
    "Carex cumulata", "Carex digitalis var. digitalis", "Carex echinodes", 
    "Carex folliculata", "Carex formosa", "Carex hirsutella", "Carex laxiculmis var. laxiculmis", 
    "Carex lupuliformis", "Carex macloviana -p11", "Carex molesta", 
    "Carex muehlenbergii var. muehlenbergii", "Carex oligocarpa", 
    "Carex richardsonii", "Carex sartwellii", "Carex siccata", "Carex swanii", 
    "Carex sychnocephala", "Carex tincta", "Carex trichocarpa", "Carex typhina", 
    "Carex virescens", "Carya ovata var. ovata", "Catharus bicknelli", 
    "Ceanothus americanus", "Cephaloziella rubella var. sullivantii", 
    "Cephaloziella uncinata", "Cerastium nutans var. nutans", "Cerastium regelii", 
    "Ceratodon heterophyllus", "Chaetura pelagica", "Charadrius melodus melodus", 
    "Chenopodium foggii", "Chimaphila maculata", "Chlidonias niger", 
    "Cicuta maculata var. victorinii", "Cinclidium latifolium", "Cistothorus stellaris", 
    "Claytonia virginica", "Clevea hyalina", "Climacium americanum", 
    "Cochlearia tridactylites", "Conopholis americana", "Corallorhiza odontorhiza var. odontorhiza", 
    "Corallorhiza striata var. striata", "Corallorhiza striata var. vreelandii", 
    "Coregonus artedi pop. 1", "Corema conradii", "Coryphopteris simulata", 
    "Coturnicops noveboracensis", "Crataegus brainerdii", "Crataegus canadensis", 
    "Crataegus coccinioides", "Crataegus crus-galli var. crus-galli", 
    "Crataegus schuettei var. schuettei", "Crataegus suborbiculata", 
    "Crocanthemum canadense", "Ctenidium subrectifolium", "Cuscuta polygonorum", 
    "Cyperus dentatus", "Cyperus erythrorhizos", "Cyperus houghtonii", 
    "Cyperus odoratus", "Cyperus schweinitzii", "Cyperus subsquarrosus", 
    "Cystopteris laurentiana", "Deschampsia alpina", "Descurainia pinnata subsp. brachycarpa", 
    "Desmodium paniculatum var. paniculatum", "Desmognathus fuscus", 
    "Diadophis punctatus edwardsii", "Dichelyma uncinatum", "Dicranella staphylina", 
    "Dicranodontium denudatum", "Didymodon maschalogena", "Diplophyllum obtusatum", 
    "Ditrichum pallidum", "Draba arctica", "Draba cayouettei", "Draba corymbosa", 
    "Draba micropetala", "Draba nemorosa", "Draba pilosa", "Draba puvirnituqii", 
    "Draba pycnosperma", "Draba subcapitata", "Drepanocladus arcticus", 
    "Echinochloa walteri", "Eleocharis aestuum", "Eleocharis compressa var. compressa", 
    "Eleocharis diandra", "Eleocharis mamillata subsp. mamillata", 
    "Elliptio crassidens", "Elymus villosus", "Encalypta affinis subsp. affinis", 
    "Encalypta brevipes", "Encalypta longicollis", "Endogemma caespiticia", 
    "Ephemerum serratum", "Epilobium saximontanum", "Eremonotus myriocarpus", 
    "Erigeron compositus", "Erigeron compositus –p01, p11", "Erigeron philadelphicus var. provancheri", 
    "Eriocaulon parkeri", "Erythranthe geyeri", "Esox americanus vermiculatus", 
    "Esox niger", "Eurybia divaricata", "Eurynia dilatata", "Falco peregrinus pop. 1", 
    "Festuca baffinensis -p11", "Festuca frederikseniae", "Fissidens exilis", 
    "Fissidens fontanus", "Fissidens grandifrons", "Fissidens obtusifolius", 
    "Fissidens subbasilaris", "Floerkea proserpinacoides", "Forsstroemia trichomitria", 
    "Frullania brittoniae", "Frullania inflata var. communis", "Frullania riparia", 
    "Fuscocephaloziopsis macrostachya var. macrostachya", "Galium brevipes", 
    "Gaylussacia bigeloviana", "Gentiana clausa", "Gentianella propinqua subsp. propinqua -p09, p11", 
    "Gentianopsis virgata subsp. macounii", "Gentianopsis virgata subsp. victorinii", 
    "Geranium carolinianum", "Glaucomys volans pop. 1", "Grimmia atrata", 
    "Grimmia crinitoleucophaea", "Grimmia incurva", "Grimmia mollis", 
    "Grimmia olneyi", "Grimmia pilifera", "Grimmia sessitana", "Grimmia teretinervis", 
    "Grimmia trichophylla", "Gymnocarpium continentale", "Gymnocolea inflata subsp. acutiloba", 
    "Gymnomitrion obtusum", "Gymnomitrion revolutum", "Gyrinophilus porphyriticus pop. 2", 
    "Haliaeetus leucocephalus", "Helianthus divaricatus", "Hemidactylium scutatum", 
    "Histrionicus histrionicus pop. 1", "Homalosorus pycnocarpos", 
    "Hordeum brachyantherum subsp. brachyantherum", "Hybognathus hankinsoni", 
    "Hydrobates leucorhous pop. 1", "Hydroprogne caspia", "Hygroamblystegium noterophilum", 
    "Hygrobiella laxifolia", "Hygrohypnum montanum", "Hygrohypnum subeugyrium", 
    "Hylodesmum nudiflorum", "Hyophila involuta", "Hypericum ascyron subsp. pyramidatum", 
    "Hypericum gentianoides", "Hypericum virginicum", "Hypnum callichroum", 
    "Ichthyomyzon fossor", "Information masquée", "Ionactis linariifolia", 
    "Iris virginica var. shrevei", "Ixobrychus exilis", "Juglans cinerea", 
    "Juncus acuminatus", "Juncus greenei", "Juncus longistylis", 
    "Juncus torreyi", "Jungermannia atrovirens", "Jungermannia polaris", 
    "Justicia americana", "Lampropeltis triangulum", "Lathyrus venosus", 
    "Lepomis peltastes", "Leptodea fragilis", "Leskea obscura", "Lespedeza capitata", 
    "Liparis liliifolia", "Lithobates palustris", "Lophozia silvicola", 
    "Lophozia ventricosa var. uliginosa", "Lysimachia hybrida", "Mannia fragrans", 
    "Mannia gracilis", "Mannia pilosa", "Marchantia polymorpha subsp. montivagans", 
    "Marsupella aquatica", "Marsupella boeckii", "Marsupella condensata", 
    "Marsupella sparsifolia", "Melica smithii", "Mesoptychia bantriensis", 
    "Micranthes gaspensis", "Micranthes stellaris", "Microlejeunea ulicina", 
    "Micromitrium tenerum", "Microtus chrotorrhinus", "Microtus pinetorum", 
    "Moerckia blyttii", "Moxostoma carinatum", "Moxostoma hubbsi", 
    "Muhlenbergia sylvatica", "Muhlenbergia tenuiflora", "Mulgedium pulchellum", 
    "Mustela nivalis", "Myosotis verna", "Myoxocephalus thompsonii", 
    "Myriophyllum heterophyllum", "Myriophyllum humile", "Najas gracillima", 
    "Najas guadalupensis subsp. olivacea", "Nardia insecta", "Nardia scalaris", 
    "Nardus stricta", "Neottia bifolia", "Neottia borealis", "Nerodia sipedon sipedon", 
    "Notothylas orbicularis", "Notropis bifrenatus", "Notropis rubellus", 
    "Noturus flavus", "Noturus insignis", "Nuttallanthus canadensis", 
    "Obovaria olivaria", "Oenothera gaura", "Oenothera pilosella", 
    "Oligotrichum falcatum", "Opheodrys vernalis", "Ophioglossum pusillum", 
    "Orthothecium chryseon var. cochleariifolium", "Orthotrichum pallens", 
    "Osmerus mordax pop. 1", "Oxytropis borealis var. viscida", "Oxytropis deflexa subsp. foliolosa -p11", 
    "Packera heterophylla", "Packera obovata", "Panicum flexile", 
    "Panicum philadelphicum", "Panicum virgatum", "Pedicularis palustris subsp. palustris", 
    "Pelekium minutulum", "Pellaea atropurpurea", "Pellaea glabella subsp. glabella", 
    "Peltandra virginica", "Penstemon hirsutus", "Percina copelandi", 
    "Perimyotis subflavus", "Persicaria arifolia", "Persicaria careyi", 
    "Persicaria robustior", "Phascum cuspidatum", "Phoca vitulina mellonae", 
    "Phragmites australis subsp. americanus", "Physcomitrella patens", 
    "Physostegia virginiana subsp. virginiana", "Pinus rigida", "Plagiomnium curvatulum", 
    "Platanthera flava var. herbiola", "Platanthera unalascensis", 
    "Platylomella lescurii", "Poa saltuensis subsp. languida", "Poa secunda subsp. secunda var. secunda", 
    "Podiceps auritus", "Podophyllum peltatum", "Podostemum ceratophyllum", 
    "Pohlia melanodon", "Polanisia dodecandra subsp. dodecandra", 
    "Polemonium vanbruntiae", "Polygala ambigua", "Polygala polygama", 
    "Polygala senega", "Polygonum douglasii", "Polypodium sibiricum", 
    "Polystichum scopulinum", "Polytrichastrum ohioense", "Potamilus alatus", 
    "Potamogeton berchtoldii subsp. gemmiparus", "Potamogeton illinoensis", 
    "Potamogeton strictifolius", "Potamogeton vaseyi", "Potentilla arenosa subsp. chamissonis", 
    "Proserpinaca palustris", "Prunus pumila var. susquehanae", "Pseudacris maculata", 
    "Pseudacris triseriata", "Pseudoleskea stenophylla", "Psilopilum cavifolium", 
    "Puccinellia angustata", "Puccinellia nuttalliana", "Pycnanthemum tenuifolium", 
    "Quercus bicolor", "Racomitrium canescens subsp. latifolium", 
    "Racomitrium panschii", "Rangifer tarandus caribou pop. 14", 
    "Rangifer tarandus caribou pop. 2", "Ranunculus sulphureus", 
    "Rhizomnium andrewsianum", "Rhus aromatica var. aromatica", "Rhynchospora capillacea", 
    "Rhytidiadelphus loreus", "Riccia beyrichiana", "Riccia bifurca", 
    "Riccia cavernosa", "Riccia frostii", "Riccia rhenana", "Riccia sorocarpa", 
    "Riparia riparia", "Rorippa aquatica", "Sabulina litorea", "Sabulina michauxii", 
    "Sabulina rossii", "Saccobasis polita", "Sagina nodosa subsp. nodosa", 
    "Sagina saginoides -p01, p11", "Sagittaria montevidensis subsp. spongiosa", 
    "Salix amygdaloides", "Salix arbusculoides", "Salix chlorolepis", 
    "Salix maccalliana", "Salix pseudomonticola", "Salvelinus alpinus oquassa", 
    "Samolus parviflorus", "Sanicula canadensis var. canadensis", 
    "Sanionia orthothecioides", "Saururus cernuus", "Sauteria alpina", 
    "Scapania carinthiaca var. carinthiaca", "Scapania glaucocephala var. glaucocephala", 
    "Scapania irrigua subsp. rufescens", "Scapania kaurinii", "Scapania pseudocalcicola", 
    "Scapania scandica", "Sceptridium oneidense", "Schistidium atrichum", 
    "Schistidium crassipilum", "Schistidium flexipile", "Schistidium frigidum", 
    "Schistidium holmenianum", "Schistidium pulchrum", "Schistidium venetum", 
    "Schistochilopsis grandiretis", "Schizaea pusilla", "Schoenoplectiella purshiana var. purshiana", 
    "Schoenoplectus heterochaetus", "Scirpus ancistrochaetus", "Sedum villosum", 
    "Seligeria brevifolia", "Seligeria diversifolia", "Seligeria recurvata", 
    "Setophaga cerulea", "Sisyrinchium angustifolium", "Solidago chlorolepis", 
    "Sorex dispar", "Sorex gaspensis", "Sphagnum aongstroemii", "Sphagnum mirum", 
    "Sphagnum orientale", "Sphagnum perfoliatum", "Sphagnum rubiginosum", 
    "Sphagnum strictum", "Spiranthes casei var. casei", "Sporobolus compositus var. compositus", 
    "Stegonia latifolia var. latifolia", "Stegonia latifolia var. pilifera", 
    "Stellaria alsine", "Sterna dougallii", "Storeria dekayi", "Strophostyles helvola", 
    "Symphyotrichum anticostense", "Symphyotrichum lanceolatum subsp. lanceolatum var. interior", 
    "Symphyotrichum laurentianum", "Symphyotrichum pilosum var. pringlei", 
    "Symphyotrichum robynsianum -p07, p15", "Symphyotrichum subulatum var. subulatum", 
    "Synaptomys cooperi", "Taenidia integerrima", "Taraxacum latilobum", 
    "Taraxacum laurentianum", "Tayloria acuminata", "Tetraplodon pallidus", 
    "Tetrodontium brownianum", "Tetrodontium ovatum", "Tetrodontium repandum", 
    "Thalictrum dasycarpum", "Thamnophis saurita septentrionalis", 
    "Thelia hirtella", "Timmia sibirica", "Tofieldia coccinea", "Torreyochloa pallida var. pallida", 
    "Tortella inclinata", "Tortula laureri", "Tortula leucostoma", 
    "Tortula nevadensis", "Toxicodendron vernix", "Trichophorum pumilum", 
    "Trichostema brachiatum", "Trichostema dichotomum", "Tritomaria capitata", 
    "Tritomaria laxa", "Tritomaria quinquedentata subsp. turgida", 
    "Utricularia radiata", "Utterbackiana implicata", "Valeriana uliginosa", 
    "Verbena stricta", "Vermivora chrysoptera", "Veronica alpina", 
    "Veronica catenata", "Viburnum recognitum", "Vicia americana var. americana", 
    "Viola rostrata", "Viola sagittata var. ovata", "Viola sagittata var. sagittata", 
    "Woodsia oregana subsp. cathcartiana", "Woodsia scopulina subsp. laurentiana", 
    "Zygodon rupestris")

#------------------------------------------------------------------------------
# 1. Select species and years
#------------------------------------------------------------------------------
sp_name <- SPECIES_LIST[ARRAY_ID]


#------------------------------------------------------------------------------
# 2. Compute SPI
#------------------------------------------------------------------------------
SPI <- run_SPI_computation(sp_name, YEARS_LIST, PROTECTED_AREA_TYPE, UNION)


#------------------------------------------------------------------------------
# 2. Save SPI
#------------------------------------------------------------------------------
write.csv(SPI, paste0("results/", gsub(" ", "_", sp_name), ".csv"))
